src/Extractor.cc
I have changed the way of checking if volumes are empty or not.
Previously it was based on material density but now it is based on material list.
=> Add warning messages when mass-less volumes are found and skipped.

include/tk2CMSSW_strings.h, src/Extractor.cc, src/XMLWriter.cc, xml/pixbar.xml, xml/pixfwd.xml, xml/trackerStructureTopology.xml
CMSSW_6_2_SLHCDEV_X_2015-06-05-2300 was used
Tested with : 13000_FourMuPt1_200+FourMuPt_1_200_Extended2023Muon_GenSimHLBeamSpotFull+DigiFull_Extended2023Muon+RecoFull_Extended2023Muon+HARVESTFull_Extended2023Muon
=> xml from tkLayout work now out of the box for CMSSW_6_2_SLHCDEV_X

CMakeLists.txt, CMakeUninstall.cmake, GetGitVersion.cmake, README.md, setupCMake_slc6.sh
Merging CMake by @drasal into dev (after manual conflict resolution)
=> CMake support from drasal

include/global_constants.h, src/Analyzer.cpp, src/InactiveElement.cc
Removing unnecessary #define of E and PI
=> Code cleanup

CMakeLists.txt, CMakeUninstall.cmake, README.md, doc/Doxyfile, src/PixelExtractor.cc, src/delphize.cpp
Delphize program works out tkLayout results and provides on the output standard Delphes card for a tracker. In addition Cmake now generates documentation based on Doxygen, simply using make doc. Command make uninstall removes the generated html directory in doc direcotry. Finally, fixed big PI -> M_PI (probably forgotten during removing PI constant from a program).
=> DevDelphes - added delphize program + CMake can generate doc now automatically.

include/Units.h
Use units as follows:
double energy = 10 * Units::GeV;
std::cout << "Energy = " << energy / Units::MeV << std::endl
=> Added Units constants

include/Barrel.h, include/Endcap.h, include/SupportStructure.h, include/global_constants.h, src/Analyzer.cpp, src/Barrel.cpp, src/Endcap.cpp, src/MatCalcDummy.cc, src/Materialway.cpp, src/Squid.cc, src/SupportStructure.cpp, src/Tracker.cpp, src/Usher.cc, src/Vizard.cc
Apply this pull request after pull request #101
=> Dev const - removed geometry hard-coded numbers and replace them with const.

include/Barrel.h, include/Endcap.h, include/SupportStructure.h, include/global_constants.h, src/Analyzer.cpp, src/Barrel.cpp, src/Endcap.cpp, src/MatCalcDummy.cc, src/Materialway.cpp, src/Squid.cc, src/SupportStructure.cpp, src/Tracker.cpp, src/Usher.cc, src/Vizard.cc
Removed hardcoded numbers in Vizard.cc: sizes of canvases and ranges of resolution plots, visualisation constants (vis_) applied instead.
Apply after pull request #102
=> Dev const vis: Removed hardcoded numbers - canvas sizes & resolution plots ranges

include/Analyzer.h, include/Barrel.h, include/Endcap.h, include/SupportStructure.h, include/global_constants.h, src/Analyzer.cpp, src/Barrel.cpp, src/Endcap.cpp, src/MatCalcDummy.cc, src/Materialway.cpp, src/Squid.cc, src/SupportStructure.cpp, src/Tracker.cpp, src/Usher.cc, src/Vizard.cc
Removed hardcoded field of eta regions from Analyzer and Vizard, instead global constant eta field (numbers & corresponding names) applied!
Apply after #103
=> Dev const eta regions: Removed hardcoded field of eta regions from Analyzer and Vizard

include/Analyzer.h, include/Bag.h, include/Barrel.h, include/Endcap.h, include/SupportStructure.h, include/Vizard.h, include/global_constants.h, src/Analyzer.cpp, src/Bag.cpp, src/Barrel.cpp, src/Endcap.cpp, src/MatCalcDummy.cc, src/Materialway.cpp, src/Squid.cc, src/SupportStructure.cpp, src/Tracker.cpp, src/Usher.cc, src/Vizard.cc
Added simulation of tracker(s) resolution for given total momenta (not just pT), visualisation adapted accordingly, arranged full layout to be positioned at the top of Index web page.
Apply after #104
=> Dev p mom - Added simulation of tracker(s) resolution for given total momenta

include/Analyzer.h, include/Bag.h, include/Barrel.h, include/DetectorModule.h, include/Endcap.h, include/SupportStructure.h, include/Vizard.h, include/global_constants.h, src/Analyzer.cpp, src/Bag.cpp, src/Barrel.cpp, src/DetectorModule.cpp, src/Endcap.cpp, src/MatCalcDummy.cc, src/Materialway.cpp, src/Squid.cc, src/SupportStructure.cpp, src/Tracker.cpp, src/Usher.cc, src/Vizard.cc
Fixed bug in a couldHit procedure calculating cross-section of track and module. The bug was in phi when crossing +pi -> -pi cross-line. All modules provide min, max phi in -pi;+3pi interval to avoid this problem.
Apply after #105
=> Dev phi issue - problem with min & max phi calculation when crossing +pi/-pi line.

config/stdinclude/CMS_Phase2/Pixel/Resolutions/Endcap_50x200, src/Analyzer.cpp
=> Revert "New cfg file for Endcap Large Rectangular pixel resolution"

CMakeLists.txt, src/Analyzer.cpp
I have removed the continue command and put curl brackets instead in the check that parabolic approximation is valid during tracking analysis ...
=>  Pruning - Don't consider tracks breaking the parabolic approximation

src/Analyzer.cpp
Thanks to Gabrielle corrected an obvious bug:
nHits must be higher than 2, otherwise track not taken into account. Removed the condition for all tracks, done separately for all options: pT, pT ideal, p, p ideal ...
=> Pruning - corrected bug nHits<=2 to nHits>2

include/GraphVizCreator.hh, include/Squid.h, include/Vizard.h, include/mainConfigHandler.h, src/GraphVizCreator.cpp, src/Squid.cc, src/Vizard.cc, src/mainConfigHandler.cpp, src/tklayout.cpp
Implementing a new @include system (see commit 1892fdd for details)
Better web output for the include tree (with the option -w)
=> New include system

.gitignore, doc/algorithms/.gitignore, include/Vizard.h, src/Vizard.cc, test/.gitignore
Fixes #96 
UNTESTED - please test before merging
=> Geometry files for pixels too

include/Vizard.h, src/Vizard.cc
=> Dev eta error

include/Vizard.h, src/Vizard.cc
+ Moving geometry files to the geometry section.
=> Cherry-pick from Stefano : Each tracker has its geometry files now.

src/Analyzer.cpp
Locally tested on studiesPixelGeometries branch by Stefano
=> Micro-patch: fixingg hte content of the delta(p) vs. eta plot

include/Extractor.h, include/XMLWriter.h, include/tk2CMSSW_datatypes.h, include/tk2CMSSW_strings.h, src/Extractor.cc, src/Materialway.cpp, src/XMLWriter.cc, src/tk2CMSSW.cc, xml/pixbar.xml, xml/pixfwd.xml, xml/trackerVolumeTemplate.xml
TO DO : Check whether the new geometry for TB2S doesn't cause any regression regarding overlaps (outermost container volumes have static boundaries for the moment)
=> Solved all overlaps within Tracker volume + between Tracker & beam pipe, for the retained layout (Baseline_tilted_200_Pixel_4_0_2_1)

geometries/CMS_Phase2/OT_Tilted_360_200_Pixel_4021.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/OT_V360_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TB2S_V351_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TBPS_V360_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD1_V351_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V351_200.cfg
=> Adding most recent tilted barrel

include/Analyzer.h, include/Vizard.h, src/Analyzer.cpp, src/Vizard.cc
Both in the geometry page of each tracker and the info page
=> New plots with number of hit layers

include/Vizard.h, src/Vizard.cc
Tested by Stefano: works as intended
=> Adding resolution on ctau in the summary page

source/Analysis/include/AnalyzerResolution.h, source/Analysis/src/AnalysisManager.cc, source/Analysis/src/AnalyzerResolution.cc, source/Tools/include/CsvTextBuilder.h, source/Tools/src/CsvTextBuilder.cc
* added csv output and published on the Info site (changed AnalysisManager Info part accordingly)
=> DevLite - Finished tracking resolution studies

geometries/CMS_Phase2/OT_Tilted_362_200_Pixel_4022.cfg, geometries/CMS_Phase2/OT_Tilted_462_200_Pixel_4021.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/OT_V462_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TB2S_V460_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TBPS_V462_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD1_V451_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V451_200.cfg, geometries/CMS_Phase2/Pixel/Pixel_V4/BPIX_4_2_0.cfg, geometries/CMS_Phase2/Pixel/Pixel_V4/Pixel_V4_0_2_2.cfg, geometries/CMS_Phase2/readme.txt
Adding a pixel configuration with smaller radii for layer 3 and 4 (4.0.2.2, based on 4.0.2.1)
Adding an Outer Tracker configuration with paired-up layers (4.6.2, based on 3.6.2)
=> Two new layouts

src/Vizard.cc
Added in geometry csv files in the website : 
- modules tilt angles;
- modules width and length;
- sensorThickness.
Also improved display of info in csv files.
=> Added geometry info in csv files on website

include/PlotDrawer.h, src/PlotDrawer.cpp, src/Vizard.cc
- There is now a proper Eta frame for all plots on website.
- Added extra geometry info on geometry tab / corrected wrong info in the case of several Endcaps.
Probably more info should be added, please let me know what you need :)
=> Important corrections on website in geometry tab

src/Squid.cc, src/Vizard.cc
Output improvement: table with number of modules
Usage improvement: tklayout can now be run from any directory
=> Small improvements

include/Sensor.h, include/Vizard.h, include/capabilities.h, src/Vizard.cc
DetId info appears : 
- on the geometry tabs : geometry files have an additional column with matching DetIds.
- on the info tab : summary list of all DetIds and their matching geometry info.
=> Added DetId info on the website

config/stdinclude/CMS_Phase2/Pixel/ModuleMaterials/Components/pixel_Chip_Caps
All the recent code for material budget will be pushed soonish.
In the meantime, this important bug fix is pushed.
=> Fixed Pixel Chip Capacitors cfg file : componentName and targetVolume were missing

include/Vizard.h, include/rootweb.hh, src/Squid.cc, src/Vizard.cc, src/rootweb.cpp
Info page as first one
Alpha parameter shown in info page
Transverse plane views of whole detector also in info page
Long (confusing) list of configuration files hidden in info page
Coding style improvements
Some whitespaces removed
Summary root file should not have illegal characters any more (no objects with any ".-()" in their name)
=> Improvements in website render (info page)

include/Analyzer.h, src/Analyzer.cpp
=> Fixed typo noticed by Stefano

geometries/CMS_Phase2/Pixel/Pixel_V4/Pixel_V4_0_2_5.cfg, include/global_constants.h, src/Materialway.cpp
=> Making supports thinner (2mm)

geometries/CMS_Phase2/OT365_200_IT4026.cfg, geometries/CMS_Phase2/Pixel/Pixel_V4/FPIX2_4_0_2_6.cfg, geometries/CMS_Phase2/Pixel/Pixel_V4/Pixel_V4_0_2_6.cfg, geometries/CMS_Phase2/Pixel/Pixel_V4/stations_FPIX_2_4_Service_Cylinder_near, geometries/CMS_Phase2/readme.txt
(based on 4.0.2.5 but with 7 FPIX fisks)
=> Creating Inner Tracker version 4.0.2.6

config/stdinclude/CMS_Phase2/Pixel/Materials/disk_FPIX, config/stdinclude/CMS_Phase2/Pixel/Materials/disk_FPIX_2, config/stdinclude/CMS_Phase2/Pixel/Materials/rod_BPIX_L2
Tuning the wiring for FPIX matching the doc:
https://indico.cern.ch/event/590539/contributions/2389311/attachments/1384483/2108652/ServicesPixel4025.xlsx
=> Material update

config/stdinclude/CMS_Phase2/Pixel/Materials/disk_FPIX, config/stdinclude/CMS_Phase2/Pixel/Materials/disk_FPIX_2
=> Revert "Material update"

config/stdinclude/CMS_Phase2/Pixel/Materials/disk_FPIX, config/stdinclude/CMS_Phase2/Pixel/Materials/disk_FPIX_2
=> Revert "Revert "Material update""

include/DetectorModule.h, include/Vizard.h, include/global_constants.h, src/AnalyzerVisitors/IrradiationPower.cpp, src/Vizard.cc
=> Added sensors irradiation csv files

geometries/CMS_Phase2/OuterTracker/Tilted/TBPS_V366_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V366_200.cfg
Updating a (tentative) smallDelta in TBPS_flat
=> Fixing TEDD_2 (where the proper bigDelta was not applied)

geometries/CMS_Phase2/OuterTracker/Tilted/TBPS_V366_200.cfg
Updating the tilted part to take into account the new 12th ring by Kamil
=> Updating The TBPS flat part to include CML new plank thicknesses

geometries/CMS_Phase2/OT463_200_IT4025.cfg, geometries/CMS_Phase2/OT466_200_IT4025.cfg, geometries/CMS_Phase2/OT467_200_IT4025.cfg, geometries/CMS_Phase2/OT468_200_IT4025.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/OT_V463_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/OT_V466_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/OT_V467_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/OT_V468_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V463_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V466_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/Timing_V466.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/Timing_V467.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/Timing_V468.cfg, geometries/CMS_Phase2/readme.txt
=> Revert "Revert "Dev gabie""

geometries/CMS_Phase2/OT377_200_IT4025.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/OT_V377_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD1_V377_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V377_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD3_V377_200.cfg, geometries/CMS_Phase2/readme.txt
=> Adding the TEDD constrained with ring-shift optimization

include/PlotDrawer.h, src/Vizard.cc
=> Limiting the hybrid drawing to the endcap plot.

config/stdinclude/CMS_Phase2/OuterTracker/Materials/MechanicalSupports/SupportsEndcapTEDD_V3_5_1.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V601_200.cfg, src/Extractor.cc, xml/pixbar.xml, xml/pixfwd.xml
Overlaps/ extrusions : 
- TBPS was extruding its mother volume
-  boundary OT with TEDD
- TEDD support structure extruding mother volume
=> SOLVED ALL OVERLAPS IN TRACKER for geometry OT6111 + TEDD_2 support was present twice

Makefile, include/Report.hh, include/ReportModuleCount.hh, include/TrackerBundle.hh, include/Visitor.h, src/ReportModuleCount.cpp, src/Vizard.cc
split by module type (incl. sensor spacing) and subdetector
Using a new Report paradigm, with analyze on tracker(s) and visualize separately
=> New module count table

config/stdinclude/CMS_Phase2/OuterTracker/ModuleTypes/ptPSlarger, src/mainConfigHandler.cpp
=> Revert "Dev"

include/Analyzer.h, src/Analyzer.cpp, src/PtErrorAdapter.cpp, src/Vizard.cc, src/mainConfigHandler.cpp, src/ptError.cpp
Several changes:
* Fix to ptError calculations (trigger output) -> correctly implemented default units. Necessary to make compatible the previous code with trigger output!
* Updated Pattern recognition module with new functionality - outside-in approach
=> Dev gabie - added outside-in pattern recognition

Makefile, install.sh
(Makefile did not make setup and new name of the binary in install.sh)
=> Fixing broken install

geometries/CMS_Phase2/OT469_200_IT4025.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/OT_V469_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V469_200.cfg, geometries/CMS_Phase2/readme.txt
Timing : V400 (Lindsey's).
OT : V613_200 (With last TEDD disk moved inwards of 10 cm) 
Pixel : V4025.
=> Added OT469_200_IT4025.cfg : Lindsey timing layer (with 1x3 mm2 pads) plugged on TDR layout

geometries/CMS_Phase2/OT613_200_IT408.cfg, geometries/CMS_Phase2/Pixel/Pixel_V4/FPIX1_4_0_8.cfg, geometries/CMS_Phase2/Pixel/Pixel_V4/FPIX2_4_0_8.cfg, geometries/CMS_Phase2/Pixel/Pixel_V4/Pixel_V4_0_8.cfg, geometries/CMS_Phase2/Pixel/Pixel_V4/stations_FPIX1_4_0_8_Service_Cylinder_near, geometries/CMS_Phase2/Pixel/Pixel_V4/stations_FPIX2_4_0_8_Service_Cylinder_near, geometries/CMS_Phase2/readme.txt
Layout is called IT 408.
It is based from IT 4025 (TDR layout).
minZ and maxZ of each FPX block are the same as for  IT 4025.
=> Added Inner Tracker layout with (7+3) disks in FPX

geometries/CMS_Phase2/OT614_200_IT404.cfg
Nothing new here: 
Just plug the existing OT 614 on the existing IT 404.
This is this combination of (OT + IT) which is integrated within CMSSW.
=> Added layout OT614 IT404. 

src/ReportIrradiation.cc
The Modules DetIds info is added on the irradiation csv files.
Please see at the bottom of the irradiation (outer) and irradiation (pixels) tabs.
=> Added Modules DetIds <-> fluence mapping (both IT and OT tabs).

geometries/CMS_Phase2/OT616_200_IT404.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/OT_V616_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TB2S_V616_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD1_V616_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V616_200.cfg, geometries/CMS_Phase2/readme.txt
http://ghugo.web.cern.ch/ghugo/layouts/test/OT616_200_IT404/layout.html
=> Outer Tracker: leave space for BTL and IT insertion.

geometries/CMS_Phase2/Pixel/Pixel_V4/BPIX_4_4_6_0.cfg, geometries/CMS_Phase2/Pixel/Pixel_V4/FPIX1_4_6_1.cfg, geometries/CMS_Phase2/Pixel/Pixel_V4/Pixel_V4_6_0.cfg, geometries/CMS_Phase2/Pixel/Pixel_V4/Pixel_V4_6_1.cfg, geometries/CMS_Phase2/Pixel/Pixel_V4/stations_BPIX_Service_Cylinder_V2, geometries/CMS_Phase2/Pixel/Pixel_V4/stations_FPIX_1_Service_Cylinder_V2, geometries/CMS_Phase2/readme.txt
NB: Also slightly reduce size of TFPX stations with latest data (IT 460 and IT 461).
=> IT 461: Update positions of TBPX conversion stations with data from Yadira

include/PlotDrawer.hh, src/OuterCabling/ModulesToBundlesConnector.cc, src/Vizard.cc
Evth is at: http://ghugo.web.cern.ch/ghugo/layouts/test/OT616_200_IT404/cablingOuter.html
=> TEDD, (-Z) end: Add modules <-> MFB fanouts branches cabling

CMakeLists.txt, include/Materialway.hh, setupCMake_slc6.sh
=> CMake CleanUp

src/AnalyzerVisitors/GeometricInfo.cc, src/Vizard.cc
=> Add # chips and # channels per module info on IT cabling csv

src/Analyzer.cc
Results would be wrong when theta is in [Pi/2 Pi], which is not used in practice, but could be dangerous.
=> Mini-PR: avoid dangerous corner case

geometries/CMS_Phase2/OT616_IT614.cfg, geometries/CMS_Phase2/Pixel/Pixel_V6/BPIX_6_1_4.cfg
=> Mini-PR: forgot to add file gathering OT and IT.

geometries/CMS_Phase2/readme.txt
Forgot to add IT 614 to readme.
See PR #509 .
=> Mini-PR: update readme.

include/Vizard.hh, src/AnalyzerVisitors/GeometricInfo.cc, src/Squid.cc, src/Vizard.cc
- As requested by Andrea V. some time ago, add modules operating parms on website.
- Avoid misunderstanding with Mechanical engineers: the coordinates in csv files are sensors centers coordinates.
=> Info on website

config/stdinclude/CMS_Phase2/OuterTracker/Materials/MechanicalSupports/SupportsEndcapTEDDTop_V616.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/OT_V616.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/OT_V616_200.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/OT_V617.cfg, geometries/CMS_Phase2/OuterTracker/Tilted/OT_V618.cfg, xml/pixbar.xml, xml/pixfwd.xml
Fixes of OT envelope, and reduction of TEDD outermost support structure radius.
Main work for PR of T20 was introduced here:
- https://github.com/tkLayout/tkLayout/pull/507/ 
- https://github.com/tkLayout/tkLayout/pull/508/
=> Additional fixes associated with PR of T20 to CMSSW

setup_centos8.sh, src/MainConfigHandler.cc
=> Proudly introducing Centos8

config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_1x2_25x100_v202305, config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_1x2_25x100_wide_2sens_3D, config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_2x2_25x100_v202305, geometries/CMS_Phase2/OT800_IT710.cfg, geometries/CMS_Phase2/OT800_IT711.cfg, geometries/CMS_Phase2/Pixel/Pixel_V7/BPIX_7_1_0.cfg, geometries/CMS_Phase2/Pixel/Pixel_V7/BPIX_7_1_1.cfg, geometries/CMS_Phase2/Pixel/Pixel_V7/Pixel_V7_1_0.cfg, geometries/CMS_Phase2/Pixel/Pixel_V7/Pixel_V7_1_1.cfg, include/CoordinateOperations.hh, include/DetectorModule.hh, include/Extractor.hh, include/Sensor.hh, include/global_constants.hh, include/tk2CMSSW_strings.hh, src/Extractor.cc, src/Hit.cc, src/Sensor.cc, src/XMLWriter.cc
3D modules now described as having two separate sensors with an air + inactive silicon gap.
See also: https://indico.cern.ch/event/1242574/contributions/5382602/attachments/2637975/4564459/em20230428.pdf
CMSSW PR to be made soon (T33)
NB: some of this code could be more optimal -  since I haven't got more time to work on this I prioritized getting a minimal version that produces correct xml's working, but someone might want to spend time in the future making this nicer. 
NB2: after this is merged in dev it would be useful to merge dev into master again.
@alkemyst let me know if you have comments
=> Add OT800_IT711 (more realistic description of TBPXL1 (3D modules)

.gitignore, Makefile, countWarningsErrors.sh, include/Histo.hh, include/Polygon3d.hh, include/Property.hh, include/SummaryTable.hh, src/Bag.cc, src/DetectorModule.cc, src/Disk.cc, src/Extractor.cc, src/Layer.cc, src/OuterCabling/ModulesToBundlesConnector.cc, src/OuterCabling/OuterCablingMap.cc, src/SummaryTable.cc, src/SupportStructure.cc, src/Track.cc, src/Vizard.cc
=> Revert "Revert "Warning-cleanup patch""

.gitignore, include/RootWeb.hh, include/Squid.hh, src/RootWeb.cc, src/Squid.cc, src/tklayout.cc
=> Creating the target directory first
