tkLayout/tkLayout

- src/Materialway.cpp
The original commit says "Fix for correct material routing in case of barrel modules with maxZ greater than the one of the corresponding layer"
And this was tested by Gabrielle to be working as expected.
> Cherry-picking from Stefano Martina's PR only the commit with the "good" fix

- include/Squid.h
- include/Vizard.h
- src/Analyzer.cpp
- src/Squid.cc
- src/Vizard.cc
- src/tklayout.cpp
With this new feature you can now run tkLayout with the -d option to get detailed information regarding the service materials.
Under the tab 'material' in a section named 'Service details' you will find a new plot indicating the positions of each service volume, identified by a number, for example:
Correspondingly a comma-separated file is linked next to this picture, where for each inactive volume all the materials are listed.
The table can easily be imported in root with the following syntax:
TTree exampleTree;
exampleTree.ReadFile("inactiveSurfacesMaterials_Outer.csv");
> Adding detailed information on material budget for services

- src/Squid.cc
- src/Vizard.cc
Solves a bug reported by Giacomo, with pixel materials not being shown in the main summary page and the corresponding detailed mass breakdown tab not being computed at all.
> Adding material summary computation also for pixel

- include/Disk.h
- include/Ring.h
- src/Disk.cpp
- src/Endcap.cpp
- src/GeometricModule.cpp
- src/Ring.cpp
Several bugs fixed:
- wedge-shaped polygons were flipped
- a small bug appeared when positioning sensors in discs (not correctly calculated optimal position to have all discs of the same layout taking into account either zError or rOverlap)
> Fixing  bug to build correctly wedge-shaped sensors in disc region

- include/PlotDrawer.h
- src/Vizard.cc
BUGFIX: drawings were not rounded to 0.1mm as intended, but (since an int was used to store the coordinates to be drawn) their contour was rounded to 1mm. Too crude!
I fixed the bug and also changed the rounding to 1 micrometer. The change was tested and working
More information on the main page regarding the positions of endcap modules.
Now we report in detail the minimum and maximum radius (useful to know the ring's "envelope) and also the "low" and "high" radius (for which the ring is expected to be fully hermetic)
> Precise drawings and better report of ring coordinates

- include/Endcap.h
Found a bug in Endcap class. Setup function calculated wrongly the minR value. It was alwasy 0 independantly on the actual minimum radius value. The reason was in a wrong initialization of minR value in the algorithm.
> Bug in minR calculation - starting value 0 instead of double::max

- include/Barrel.h
- include/Endcap.h
- include/SupportStructure.h
- include/global_constants.h
- src/Barrel.cpp
- src/Endcap.cpp
- src/Materialway.cpp
- src/Squid.cc
- src/SupportStructure.cpp
- src/Tracker.cpp
Implemented Support structures at the end-cap level (same as for barrell), removed dependecy on Structure include files (using class def.), added constants instead of hard-coded numbers for Support margins, added more-readable INFO when building structures in barrel/end-cap.
> Implemented Support structures at the end-cap level

- src/Squid.cc
- src/Vizard.cc
- src/rootweb.cpp
Worked on Vizard::createXmlSite. To sum up, the following bugs were corrected : 
- in case of run with --xml, the copy of XML files did not work
- in case new TKG_LAYOUTDIRECTORY, the copy of XML files did not work
- in case run with --xml but no --pixelxml, Warning: RootWBinaryFileList::dump() appeared 
- RootWBinaryFileList objects were not instanciated correctly
- boost::filesystem::copy_file code was replicated
- error handling was incomplete
Also : added the metadata file to the XML tab.
> Several bugs in Vizard::createXmlSite solved + added the metadata file to the XML tab

- source/Analysis/include/AnalyzerMatBudget.h
- source/Analysis/src/AnalysisManager.cc
- source/Analysis/src/AnalyzerMatBudget.cc
- source/Geometry/include/BeamPipe.h
- source/Geometry/include/DetectorModule.h
- source/Geometry/include/MaterialProperties.h
- source/Geometry/src/DetectorModule.cc
- source/Geometry/src/MaterialProperties.cc
- source/Tools/include/CsvTextBuilder.h
- source/Tools/include/Palette.h
- source/Tools/include/global_constants.h
- source/Tools/src/Palette.cc
- source/Tracking/include/Hit.h
- source/Tracking/include/Track.h
- source/Tracking/src/Hit.cc
- source/Tracking/src/Track.cc
Still several functionalities "missing":
* Hadron efficiency plot available for inidividual sub-trackers not for overall tracker yet 
* Material budget of module caps + beam-pipe done for now (MaterialBudget class removed, all done within the analyzer) -> similar approach expected for Services & Supports -> will be implemented once the Material approach in tkLayout is revised
> Dev lite - Analyzer for Material budget analysis finished

- config/stdinclude/CMS_Phase2/OuterTracker/ModuleTypes/ptPS
> Important: PS modules stub correlation should be "sameSegment" 

- config/det_id_schemes.list
- geometries/CMS_Phase2/OuterTracker/Flat/OT_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/OT_V362_200.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/Pixel_V4_0_2_1.cfg
- include/Barrel.h
- include/DetectorModule.h
- include/Disk.h
- include/Endcap.h
- include/Layer.h
- include/Ring.h
- include/RodPair.h
- include/Sensor.h
- include/Tracker.h
- include/Visitor.h
- include/capabilities.h
- include/global_constants.h
- include/global_funcs.h
- include/mainConfigHandler.h
- src/DetectorModule.cpp
- src/GeometricModule.cpp
- src/Layer.cpp
- src/Sensor.cpp
- src/Tracker.cpp
- src/mainConfigHandler.cpp
DetId schemes presently in  CMSSW_8_1_X, that is to say Phase2Subdetector5 and Phase2Subdetector4, are now implemented in tkLayout.
Now that the structure is there, it is possible to easily add a new DetId scheme if needed. 
For getting DetIds, the user needs to specify in a Tracker cfg file the DetId schemes that he wants.
For example : 
_Tracker Outer {
barrelDetIdScheme Phase2Subdetector5
endcapDetIdScheme Phase2Subdetector4
}_
DetIds are then accessible in an intuitive way : 
- for each DetectorModule m :  with m->myDetId().
- for each Sensor s :  with s->myDetId().
Please check the warning tab on the website each time you are generating DetIds, in case of problem there might be useful information in there !
As a convention, the last 2 bits are set to : 
- 0 in case of a module DetId; …
> Implemented DetId in tkLayout for entire Outer Tracker

- config/stdinclude/CMS_Phase2/SimParms
As per Duccio's slides here: https://indico.cern.ch/event/536254/ (CoolingMargins)
> New alpha parameter 5.3E-17 -> 4.28E-17

- include/AnalyzerVisitors/TriggerProcessorBandwidth.h
- src/AnalyzerVisitors/TriggerProcessorBandwidth.cpp
- src/Vizard.cc
- Use of the freshly implemented Detids (matching CMSSW scheme) for identifying modules in the connections : 
a) from Trigger towers to Modules.
b) from Modules to Trigger towers
- Removal of the old sebCoords identification scheme.
> Use of DetIds for identifying modules in Trigger towers to Modules connections (and in Modules to Trigger towers connections)

- include/Extractor.h
- include/MaterialTable.h
- src/Extractor.cc
- src/MaterialTable.cc
This is temporary, as this aspect of the code for the material will be reworked anyway.
In the meantime, it provides Z and A in an acceptable range of uncertainty.
Plus Fixed merge-ability conflict of dev_gabie into dev
> Calculating Z and A from radiation length and nuclear interaction length by Stefano (code just copied pasted here).

- src/AnalyzerVisitors/TriggerProcessorBandwidth.cpp
Let's discuss this in real, maybe there is no bug and I am mistaking, but it looks like it.
NB : This has absolutely nothing to do with the extension up to 2.4, which is done on another branch.
This is about the code which calculates the eta coverage of each trigger tower.
More precisely, this is about whether MINR or MAXR of a module should be considered to check whether this module belongs to a given trigger tower.
In practice, this is a very subtle diff, and the effect of this is null on the present OT_Tilted_362_Pixel_4021 geometry and for the choice of zError=70mm.
It is unlikely that this has affected the eta coverage of trigger towers in other geometries, but not for granted at all either though.
> Bug fix in the calculation of the eta coverage of trigger tower

- config/stdinclude/CMS_Phase2/SimParms
- geometries/CMS_Phase2/OT_Tilted_362_200_Pixel_4023.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/FPIX1_4_0_2.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/FPIX2_4_0_2_3.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/Pixel_V4_0_2_3.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/stations_FPIX_2_2_Service_Cylinder_near
- geometries/CMS_Phase2/readme.txt
Creating pixel version 4.0.2.3 (=4.0.2.1 but with 8 FPIX disks and keeping 4 EXT disks)
Fixing alpha parameter, which was wrongly typed (the default value of 4.0e-17 was always used)
> New tracker model and alpha parameter fixed

- config/stdinclude/CMS_Phase2/Pixel/Resolutions/README.txt
- src/Layer.cpp
- src/RodPair.cpp
This is a subtle diff in the straight rod module placement, when building ring (i+1) with respect to ring (i) considering the zError constraint.
In the particular case where zEnd of the module in ring (i) < zError, and the build is upwards, one needs to consider : 
* -dsdistance/2. for ring (i)
* +dsdistance/2. for ring (i+1)
Indeed, this corresponds to the most stringent situation.
For all other cases, one needs to consider (and this was already the case) : 
* +dsdistance/2. for ring (i)
* -dsdistance/2. for ring (i+1)
The effect of this, for example on the flat part of TBPS, is (example with OT 364) : 
- Layer 1 : ~ 120 um shorter.
- Layer 2 : ~ 26 um shorter.
- Layer 3 : ~ 13 um shorter.
This is negligible, but incorporated at this point in time for safety reasons.
> Corrected ommission in straight rod module placement, in particular case where zEnd < zError and the build is upwards 

- include/tk2CMSSW_strings.h
- src/Extractor.cc
- src/XMLWriter.cc
- src/tk2CMSSW.cc
- xml/trackerRecoMaterial.xml
- updated tracking group names.
- updated tracking groups gathering.
- put Pixel and OT info in one file.
- off topic : warnings in extractor for wrong targetVolumes
> Quick changes to automatize the recent 'by hand' updates in XML reco material

- geometries/CMS_Phase2/OuterTracker/Tilted/TBPS_V362_200.cfg
- include/tk2CMSSW_strings.h
- src/Extractor.cc
- src/XMLWriter.cc
- xml/pixelProdCuts.xml
- xml/trackerProdCuts.xml
- Automatized in the XML export recent fixes which were 'done by hand' on trackerProdCuts.xml in CMSSW.
- Envelope of straight rod at interface flat / tilted is now fully automatic (removed hardcoded 10 mm). This was due to more stringent conditions at the flat / tilted interface (choice of parallelepiped volume for flat part rod became not sufficient to avoid overlap).
- Removed unused variable.
- All elementary materials in the XML export have now 'tkLayout_' before their names or symbol, for safety reasons.
> Additional preparation of XML export

- geometries/CMS_Phase2/Pixel/Supports/IT_Support_Tube_V1_0.cfg
- include/XMLWriter.h
- src/Extractor.cc
- src/XMLWriter.cc
- Elementary materials not duplicated in pixel.xml
- Solved all overlaps for new geometry OT365_200_IT4025 : 
There was an extrusion of freshly added IT support tube. By simply splitting it in 2 in cfg file, problem solved.
0 overlap remaining, checked by : 
- Fireworks
- Geant4 tool
> Prepare XML export for new geometries

- geometries/CMS_Phase2/FlatTracker4026.cfg
- geometries/CMS_Phase2/OuterTracker/Flat/OT_V0_200.cfg
- geometries/CMS_Phase2/OuterTracker/Flat/TB2S_V360_200.cfg
- geometries/CMS_Phase2/OuterTracker/Flat/TBPS_V0_200.cfg
- geometries/CMS_Phase2/OuterTracker/Flat/TEDD1_V351_200.cfg
- geometries/CMS_Phase2/OuterTracker/Flat/TEDD2_V351_200.cfg
- include/XMLWriter.h
- include/global_constants.h
- include/tk2CMSSW_datatypes.h
- include/tk2CMSSW_strings.h
- src/Extractor.cc
- src/XMLWriter.cc
- src/tk2CMSSW.cc
- xml/pixfwd.xml
- xml/trackerProdCuts.xml
After the merge of these commits, the code in tkLayout/dev_gabie will be in the exact state of what was used for the XML export of FlatTracker4026 and TiltedTracker4026 to CMSSW.
Updates in the XML export : 
Worked on the materials XML export.
- 'Elementary' materials : 
They are now in tracker.xml only (they were duplicated in pixel.xml).
They are prefixed by "tkLayout_" for additional safety reasons.
- Composite materials (that is to say, all the other materials !) : 
They used to be a lot of composites with different names but same actual materials compositions. Redundancies have been deleted.
Design has been chosen towards the safest solution : scan the composite materials once they are created, and print the duplicated materials only once in the XMLs.
First glance solution that …
> Latest devs in the XML export in sync with CMSSW + Added layout FlatTracker4026

- include/AnalyzerVisitors/IrradiationPower.h
- include/RodPair.h
- src/Analyzer.cpp
- src/AnalyzerVisitors/IrradiationPower.cpp
- src/Layer.cpp
- src/Vizard.cc
Until now, irradiation results for a given barrel layer, was not taking into account whether the rods are located at +bigDelta or -bigDelta.
It was randomly either of the 2 rods which was used for the results in tables on the website.
Even if the uncertainty on FLUKA data, which is used for the results, is 10% anyway, we have here a too strong simplification.
The new, more detailed, results (split tables by inner radius / outer radius rods) show :  
In the worse case (central ring of the lowest layer) : 
TB2S : -6%
TBPS : ~ +17%
Pixel barrel :  ~+19% 
(In the worse case, the diff is big enough to be worth being taken into consideration).
In the best case : 
TB2S : -1%
TBPS : ~ +2%
Pixel barrel :  ~+2% 
(In the best case, diff has no interest).
> Added a split between rods located at +bigDelta or -bigDelta in sensors irradiation power results

- geometries/CMS_Phase2/OT366_200_IT4025.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/OT_V366_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TBPS_V366_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD1_V366_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V366_200.cfg
- geometries/CMS_Phase2/readme.txt
Zd = 30.7mm
ZmPS4.0 = 14.84mm
Zm2S4.0 = 17.1mm
Zm2S4.0_R10 = 20.1mm
Zm2S1.8 = 14.9mm
No artificial gaps between rings.
Ring 15/ r_high = 1103mm
Ring 1/ r_min = 227mm disks 1-2
Ring 1/r_min = 327mm disks 3-5
Disk 1 Z = 1326.8mm
Disk 2 Z = 1550mm
Disk 3 Z = 1853.4mm
Disk 4 Z = 2216.2mm
Disk 5 Z = 2650mm
Disk 1:  R1-9  PS_4.0 modules
Disk 1:  R10:  2S_4.0 modules
Disk 1:  R11-15 2S_1.8 modules
Disk 2:  Identical to Disk 1
Disk 3:  R1-9  PS_4.0 modules
Disk 3:  R10-11:  2S_4.0 modules
Disk 3:  R12-15 2S_1.8 modules
Disk 4:  Identical to Disk 3
Disk 5:  R1-9  PS_4.0 modules
Disk 5:  R10-12:  2S_4.0 modules
Disk 5:  R13-15 2S_1.8 modules
> Updating the TEDD design according to indications by Nick (2017-02-02)

- include/AnalyzerVisitor.h
trigger tuning analysis would crash if non-pt modules are in the Outer Tracker
> Fixing an old bug

- src/Squid.cc
the "dead code" errorSummary was called even when taggedErrorSummary should have been
TODO: remove *all* code under NO_TAGGED_TRACKING
> Fixing a time-wasting bug

- include/Disk.h
- include/Endcap.h
- include/PlotDrawer.h
- include/Tracker.h
- include/Vizard.h
- src/Disk.cpp
- src/Endcap.cpp
- src/Vizard.cc
This gives a warning I do not  understand during compilation of Vizard.o:
What I do not understand is why is anEndcap const...
Building target Vizard.o...
colorgcc -std=c++11  -g -fpermissive -lstdc++ -fmax-errors=2 -Iinclude/ `root-config --cflags` -c -o lib/Vizard.o src/Vizard.cc
src/Vizard.cc: In member function ‘void insur::Vizard::createSummaryCanvasNicer(Tracker&, TCanvas*&, TCanvas*&, TCanvas*&, std::vector<TCanvas*>&)’:
src/Vizard.cc:6066:47: warning: passing ‘const Endcap’ as ‘this’ argument discards qualifiers [-fpermissive]
set<Module*> modules = anEndcap.modules();
^
In file included from include/Tracker.h:17:0,
from include/Vizard.h:44,
from src/Vizard.cc:6:
include/Endcap.h:78:16: note:   in call to ‘std::set<DetectorModule*> Endcap::modules()’
set<Module*> modules();
> Detailed plots of the different endcaps

- include/Disk.h
- include/Endcap.h
- src/Disk.cpp
- src/Endcap.cpp
Modified the rings placement in TEDD, which had issues.
For a given TEDD : 
1) Vector of dsDistances (for a disk) not taken into account properly.
For a given disk, instead of the correct vec of dsDstances, the vec of maxDsDisances was used. 
2) Vector of smallDeltas (for a disk) not taken into account properly.
For example, for OT567 , in TEDD_2 :
- Disks 1 and 2 rings radii were calculated, with the constraints that Disk 1 Ring 12 smallDelta = 7.45 (fine) and Disk 3 Ring 12 smallDelta = 7.45 (not fine).
- Disks 3 rings radii were calculated, with the constraints that Disk 1 Ring 12 smallDelta = 8.55 (not fine) and Disk 3 Ring 12 smallDelta = 8.55 (fine).
**Consequences : Disk within TEDD_2 were differnet (different radi and even different number of modules).**
NB : Very quick code, …
> Quick code to fix the issues in rings placement in TEDD

- include/Disk.h
- include/Ring.h
- src/Ring.cpp
**Solved 2 errors in TEDD phiOverlap calculation code :** 
1) The modules angle coverage should be calculated with atan instead of asin.
Indeed, it is not rMax which is actually used as argument, but rHigh.
This has a non negligible effect : 
**For example, for OT567, in TEDD_2, for each disk : 4 modules more.**
2) phiOverlap/Radius was used directly as an angle, instead of atan(phiOverlap/Radius).
This doesnt seem to have important effect, at least for OT567.
(since phiOverlap/Radius very close to 0.).
Off-topic NB : Also set rOverlap to 0. by default in the code.
> Solved 2 errors in TEDD phiOverlap calculation code

- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V711_200.cfg
Avi geometry : Corrected the Z of disk 1 in TEDD_2.
It is now equal to the Z of disk 1 in TEDD_2, in layouts OT611 and OT612.
WARNING : How was the Z of disk 2 in TEDD_2  calculated in the Avi geometry ?
If it was defined relative to disk 1, maybe it needs to be shifted as well ?
> Avi geometry : Corrected Z of first disk in TEDD_2

- geometries/CMS_Phase2/OT712_200_IT4025.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/OT_V712_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TBPS_V712_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD1_V712_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V712_200.cfg
611 (TDR layout with 'old' macro-pixel length)
612 (TDR layout with new macro-pixel length)
711 (Avi geometry with 'old' macro-pixel length)
712 (Avi geometry with new macro-pixel length)
Created  Avi geometry with new Macro Pixel length. It is called OT712.
TEDD : 
Kept same radii as 612, but with the Z that appear in 711.
TBPS : 
Layers 1 and 3 : Identical to 612.
Layer 2 : Used the same optimization process as performed for 611 -> 612.
NB : 
'Old' macro pixel-length : 32 x 1446 μm
'New' macro pixel-length : 32 x 1467 (= 46944 μm)
> Added Avi geometry with new Macro Pixel length

- config/stdinclude/CMS_Phase2/OuterTracker/ModuleTypes/ptPSlarger
- geometries/CMS_Phase2/OT613_200_IT4025.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/OT_V613_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD1_V612_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD1_V613_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V612_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V613_200.cfg
- geometries/CMS_Phase2/readme.txt
OT613_200_IT4025.cfg	Like 6.1.2 but fixing bigDelta according to Nick 2017-03-27
Zd=29.7mm or bigDelta=14.85
New geometry 6.1.3 with slight adjustment in TEDD1 and TEDD2: bigDeelta moved from 14.15mm to 14.85mm
this would cause a movement of 1.243mm and 1.351mm in innermost rings of TEDD1 and TEDD2 respectively
and add 4 modules in one ring of TEDD2.
Any ring movement was instead *avoided* by constraining the ring radii to those of 6.1.2, so that the geometry in the
xy plane is exactly the same
> New 6.1.3 geometry with correct DD separation

- include/DetectorModule.hh
- include/Hit.hh
- include/SimParms.hh
- include/TrackNew.hh
- src/Analyzer.cc
- src/Hit.cc
- src/SimParms.cc
- src/TrackNew.cc
In order to accurately study the effect of single-hit inefficiency, this was made a module-parameter
Surprisingly, this made the code run a little faster: on my laptop running with 3000 tracks on CMS-OT6.1.3-IT4.0.2.5 takes 139.7s instead of 144.5s with 95% single-hit efficiency and 112.5s instead of 117.4s for 50% single-hit efficiency.
Validation: the results are not comparable for 50% efficiency (the random effect is too large) but are compatible for 95% efficiency.
Using this patch a bug was cured: the previous parameter named efficiency was affecting the pixels too and I am not sure what efficiencyPixel was actually doing (I only noticed when trying to compare with the new behaviour). Furthermore these two parameters (which used to be in SimParms) were not designed according to the …
> Single hit efficiency is per-module

- include/tk2CMSSW_strings.hh
- src/Extractor.cc
- src/XMLWriter.cc
- src/tk2CMSSW.cc
- xml/pixbar.xml
- xml/pixelProdCuts.xml
- xml/pixelsens.xml
This quick PR includes the automation of latest updates, which were used to produce the TDR XMLs.
It includes : 
- Renamed PixelBarrel to Phase2, to match new CMMSW code by Alessia in CMSSW.
- In Inner Tracker, use Phase 1 modules local frame of reference orientation, as requested by Alessia.
NB : This issue might be risen again for the Tilted Inner Tracker, as there, the Phase 2 modules local frame of reference orientation will make more sense.
- When the shape of a volume if defined, check that volume > 0.
> Xml export : automatization of latest updates

- geometries/CMS_Phase2/OT613_200_IT500.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V5/BPIX_5_0_1.cfg
- geometries/CMS_Phase2/readme.txt
Tilted Inner Pixel BPIX_5_0_0.cfg is the layout sent to Mechanics for first-glance study.
What was done : 
- Added one ring in flat part;
- Optimized tilted part;
- Make all barrel layers have ~ same maxZ.
A posteriori, tiny adjustment in Layer 3 tilt angle and maxZ in BPIX_5_0_1.cfg.
> Tilted Inner Pixel : head of series (with Duccio).

- include/Cabling/cabling_constants.hh
- src/Cabling/Bundle.cc
- src/Cabling/Cable.cc
- src/Cabling/CablingMap.cc
- src/Cabling/ModulesToBundlesConnector.cc
- src/Cabling/PhiPosition.cc
- src/Cabling/cabling_constants.cc
This is to reduce the data rate to DTCs reading the lower radii layers.
See https://indico.cern.ch/event/651635/contributions/2663563/attachments/1493796/2323189/hugo.pdf .
Following reshuffling was done in bundles -> cables map for PS modules.
In a given Phi-Sector:
- 10 G for Slot 1: TBPS Layer 1 flat rod + TEDD disks 1, 3 , 5 (PS10G + ex-PS5GA).
- 10 G for Slot 2: TBPS Layer 1 tilted rods + TEDD disks 2, 4 (PS10G + ex-PS5GA).
- 5 G for Slot 3: TBPS Layer 2, all rods.
- 5 G for Slot 4: TEDD disks 1, 3, 5 (ex-PS5GB).
- 5 G for Slot 5: TBPS Layer 3 flat rods + TEDD disk 2 (ex-PS5GB).
- 5 G for Slot 6: TBPS Layer 3 tilted rods + TEDD disk 4 (ex-PS5GB).
Cabling map before PR:
Cabling map after PR:
Results are at http://ghugo.web.cern.ch/ghugo/layouts/July/OT613_200_IT4025/cablingOuter.html …
> Reshuffling of bundles -> cables map

- include/Analyzer.hh
- include/Hit.hh
- include/Vizard.hh
- src/Analyzer.cc
- src/Vizard.cc
Fully checked against regressions.
Added Tracking Volumes Services Detailed plots + cleaned Tracking Volume code.
Note: (Not included in this PR)
For the moment we have:
- OT tab: all MB (belonging to OT or IT) located between first OT active hit and last OT active hit.
- IT tab: all MB (belonging to OT or IT) located between first IT active hit and last IT active hit.
Now it would take not more than 1 hour to switch it to:
- OT tab: all MB belonging to OT and located until last Tracker active hit.
- IT tab: all MB belonging to IT and located until last Tracker active hit.
Shall I switch to that, or we keep things as they are?
Cheers
> Small PR: Added Tracking Volumes Services Details plots + cleaned Tracking Volume code

- src/Disk.cc
Should not display 0, but a negative value in case the interaction point is not included within the coverage interval.
> Updated calculation of zError in TEDD

- source/Geometry/include/DetectorModule.h
- source/Geometry/include/Disk.h
- source/Geometry/include/Ring.h
- source/Geometry/src/DetectorModule.cc
- source/Geometry/src/Disk.cc
- source/Geometry/src/Ring.cc
Feature copied here.
Disks on (-Z) side are presently neither mirrored, neither rotated around FCC_Y of angle Pi. 
They are now rotated around FCC_Y with angle Pi.
See #388 
Details:
The previous 'mirrorZ' was actually doing a rotation around FCC_Y and angle Pi.
But it was not working for certain geometries (case where the Ring is not invariant by rotation of axis FCC_Z and angle Pi).
> Fixed issue in Giovanni s code, spotted a while ago but pushed back.

- include/Disk.hh
- include/GeometricModule.hh
- src/Disk.cc
Make sensorThickness included in the building of rings in TEDD. 
sensorThickness was not taken into account for the building of rings in TEDD. 
It was taken into account for the calculation of zError 'a posteriori', once the rings are built.
This showed that there was a significant discrepancy introduced when not taking into account sensorThickness (zError 20 mm instead of 70 mm for example).
This is due to the fact that the disks in TEDD are far away from the interaction point, hence a tiny angular difference has big effects.
This PR allows to have the zError specified in cfg and zError calculated 'a posteriori' perfectly matching.
> Take sensorThickness into account for rings building in TEDD

- include/Cabling/Cable.hh
- include/DetectorModule.hh
- include/Palette.hh
- include/PlotDrawer.hh
- include/Vizard.hh
- src/Cabling/Cable.cc
- src/DetectorModule.cc
- src/Palette.cc
- src/Vizard.cc
- Updated services channels numbering to agreed convention: 
Channel 1A on (+Z) side becomes channel -1A on (-Z) side (when one walks along Z)
Channel 1C on (+Z) side becomes channel -1C on (-Z) side (when one walks along Z)
etc..
- Added details maps on website of routing of cables to services channels.
In all plots, +Z points towards you.
Selected examples:
Optical cabling:
Disk in TEDD:
Barrel, (+Z) cabling side.
Power cabling:
Disk in TEDD:
All detailed info is accessible at http://cms-tklayout.web.cern.ch/cms-tklayout/layouts/reference/OT613_200_IT4025/cablingOuter.html 
There is a dedicated table summarizing the channel assignments.
NB: Code related to services channels might be deeply reshaped, depending on future decisions on channels assignments designs.
> Updated services channels numbering + Added details services channels maps on website

- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD1_V613_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V613_200.cfg
- include/Disk.hh
- include/Ring.hh
- src/Disk.cc
This completes the recent efforts.
It is now possible to use, for each given ring (i) in TEDD, a radius mode or an auto mode.
- Radius mode: set the radius of the ring (i) (radiusHigh).
Example: Ring 15 { ringOuterRadius 1100 }
- Auto mode: set the zError coverage between ring (i) and ring (i+1). Ring (i) will be automatically placed accordingly. 
It is also possible to add a given radial safety distance between ring (i) and ring (i+2), called rSafetyMargin. The automatic placement will take this margin into account, and never place ring (i) closer to ring (i+2) than this margin distance.
Example: Ring 9 { zError -285 rSafetyMargin 45.0 }
Additionally, the projective z coverage info which is achieved by a given design, is calculated and displayed at (endcaps: additional info). Negative …
> TEDD design: Automatic ring placement.

- src/Cabling/Cable.cc
This is in the hypothesis optical and power cabling maps are identical (apart from channel assignment).
This is merged for having a point of reference.
Further studies have shown the need of separating optical and power cabling maps (to come in further PR).
> New services channels assignment by Duccio: Avoid power cables crossings in 2S region.

- include/InactiveElement.hh
- include/global_constants.hh
- src/Analyzer.cc
- src/InactiveElement.cc
**In this PR:**
- A) Instead of IP = (0,0,0), a flat luminous region from Z = -70 mm to Z = 70 mm is chosen for resolution studies.
- B) BUG FIX:  One should not select the Z > 0 inactive volumes only (assuming eta >= 0). Indeed, the IP can be at Z < 0, hence inactive volumes on (-Z) side can be hit.
- C) BUG FIX:  One should not select the Z > 0 sensors only (assuming eta >= 0). Indeed, the IP can be at Z < 0, hence sensors on (-Z) side can be hit.
- D) BUG FIX: Sensors tilt angle was not taken into account for crossed MB calculation, in tracking resolution studies.
- E) Improved code on hits on inactive elements. This is used to calculate hit position and crossed MB. (though, on this point, issues were rather in devLite than in master).
**Results (on OT613_200_IT404 geometry) :**
- …
> Important: Bug fixes affecting tracking resolution + Shape of luminous region for resolution studies

- include/InactiveElement.hh
- include/global_constants.hh
- src/Analyzer.cc
- src/InactiveElement.cc
In the trigger analysis, the shape of the luminous region is a gaussian Gaus(0, 70) (since several months / years?)
This appears in https://github.com/tkLayout/tkLayout/blob/master/src/Analyzer.cpp#L338 
Though, the code was only taking into consideration the sensors such that sensor.maxZ() > 0.
https://github.com/tkLayout/tkLayout/blob/master/src/Analyzer.cpp#L1478
As a result, at small trackEta, and when trackOrigin < 0, one misses to detect the sensors at Z < 0, which the track should actually cross!!
This results in an artificially low trigger efficiency at small eta!
This is fixed in this PR.
- **Before PR:**
Full results at http://ghugo.web.cern.ch/ghugo/layouts/test/OT613_200_IT404_patternreco_70luminous/triggerPerf.html 
- **After PR:**
Full results at …
> IMPORTANT: Bug fix in trigger efficiency results

- include/InactiveElement.hh
- include/global_constants.hh
- src/Analyzer.cc
- src/InactiveElement.cc
- Before PR:
- After PR:
**Details:**
- Before PR: http://ghugo.web.cern.ch/ghugo/layouts/test/OT613_200_IT404/patternReco.html 
- After PR: http://ghugo.web.cern.ch/ghugo/layouts/test/OT613_200_IT404_patternreco_70luminous/patternReco.html 
**NB:**
Set to flat luminous region from -70 mm to 70 mm for the moment.
It will be possible to set the shape of non-(0,0,0) luminous region (flat, gaussian) on demand in a future PR.
> Pattern reco studies: Switch from IP = (0,0,0) to uniform luminous region from -70 mm to 70 mm.

- source/Geometry/src/InactiveElement.cc
- source/Tools/src/GitRevision.cc
Fix InactiveElement::checkTrackHits.
The previous InactiveElement::checkTrackHits method computes several hits out of inactive volume.
The computed hitPathLength is hence sometimes huge, resulting in a non-negligible increase of the crossed MB.
This has an impact on MB and Tracking resolution.
Example on CMS Phase 2 Tracker geometry:
**Example of hit computed out of the inactive volume (before PR):**
track eta = 3.41447
trackOrigZ = -12.6505
inactive volume isVertical() = 1
inactive volume getInnerRadius() = 28.999
inactive volume getOuterRadius() = 73.557
inactive volume getZOffset() = 1103.14
inactive volume getZMax() = 1105.14
- Before PR:
hitRho = 51.242 mm
hitZ = 765.408 mm
Radiation length correction factor = 338.469
- After PR:
hitRho = 73.5508 mm
hitZ = 1104.14 mm
Radiation length …
> Fix hits on inactive elements: Effects on MB and Tracking resolution

- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_2_1x2_25x100_short
- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_2_2x2_25x100_short
- geometries/CMS_Phase2/OT614_200_IT430.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/BPIX_4_4_3_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/FPIX1_4_3_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/FPIX2_4_3_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/Pixel_V4_3_0.cfg
- geometries/CMS_Phase2/readme.txt
Inner Tracker version 4.3.0: 
smaller chip: 16.4 mm x 20 mm chip, instead of 16.4 mm x 22 mm chip (same length as Atlas).
Based from Inner Tracker version 4.0.4.
- TBPX: shorter of 18 mm.
- TFPX: First disk moved inwards of 18 mm in Z. Other disks Z positions adjusted accordingly to have the same TFPX max Z. Radii: R1 min and R4 max identical, the radii in between are adjusted (coverage). R2 center: +1 mm, R3 center: -2 mm. 
- TEPX: 4 modules added in R4. Radii: R1 min and R5 max identical, the radii in between are adjusted (coverage). R2 center: -3 mm, R3 center: -2.5 mm, R4 center: -6 mm.
> Adds IT layout with smaller chip size

- geometries/CMS_Phase2/OT614_200_IT420.cfg
- geometries/CMS_Phase2/OT614_200_IT421.cfg
This is so that the layouts presently incorporated in CMSSW are matching existing tkLayout descriptions.
Corresponding OT and IT were already described in readme.
OT614_200_IT420.cfg  <->  CMSSW D22 geometry scenario
OT614_200_IT421.cfg  <->  CMSSW D23 geometry scenario
> Plugged the IT 420 and 421 (large pixel studies) on OT614 (rotated TEDD).

- config/stdinclude/CMS_Phase2/Pixel/Materials/disk_FPIX
- config/stdinclude/CMS_Phase2/Pixel/Materials/disk_FPIX_2
- config/stdinclude/CMS_Phase2/Pixel/Materials/disk_FPIX_2500_10000
- config/stdinclude/CMS_Phase2/Pixel/Materials/disk_FPIX_2_2500_10000
TFPX: 16 serial power chains per disk.
TEPX: 28 serial power chains per disk.
NB: Also updated MB files of layouts with large pixel aspect ratio in 2x2 modules accordingly.
(The power chains MB of layouts with large pixel aspect ratio is scaled from the MB of layouts with 2500 um^2 pixels).
> TFPX and TEPX: Update serial power chains and HV lines Material Budget from Stella

- config/stdinclude/CMS_Phase2/Pixel/Materials/module_FPIX2_v2_R1_1x1_2500
- config/stdinclude/CMS_Phase2/Pixel/Materials/module_FPIX_v2_R1_1x1_2500
- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_2_1x1_25x100
- geometries/CMS_Phase2/OT614_200_IT440.cfg
- geometries/CMS_Phase2/OT614_200_IT441.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/FPIX1_4_4_1.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/FPIX2_4_4_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/FPIX2_4_4_1.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/Pixel_V4_4_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/Pixel_V4_4_1.cfg
- geometries/CMS_Phase2/readme.txt
**Inner Tracker version 4.4.0:** 
1x1 modules in TEPX Ring 1 (Swiss layout).
TEPX:  
- Ring 1: Rhigh: 108 mm -> 86 mm,  numModules: 40 -> 36.
- Ring 2: Rhigh: 149 mm -> 130 mm, numModules: 56 -> 52.
- Ring 3: Rhigh: 188.5 mm -> 171 mm.
- Ring 4: Rhigh: 232 mm -> 215 mm.
**Inner Tracker version 4.4.1:** 
Also 1x1 modules in TFPX Ring 1 (Correction by Duccio on Swiss layout).  
TFPX:
- Ring 1: Rhigh: 73.2 mm -> 51 mm.
TEPX:
- Ring 1: Rhigh: 108 mm -> 86 mm,  numModules: 40 -> 32.
- Ring 2: Rhigh: 149 mm -> 127 mm, numModules: 56 -> 48.
- Ring 3: Rhigh: 188.5 mm -> 169 mm.
- Ring 4: Rhigh: 232 mm -> 213 mm.
Using 1x1 modules allow to reduce the total silicon area (hence lower material budget).
Radii and number of modules were adjusted so that z coverage, phi coverage, and mechanical …
> Added layouts with 1x1 modules in inner rings in TFPX and / or TEPX

- include/Analyzer.hh
- include/Vizard.hh
- include/global_constants.hh
- src/Analyzer.cc
- src/Vizard.cc
Please see [various_updates.pdf](https://github.com/tkLayout/tkLayout/files/2141960/various_updates.pdf)
Notably:
Hit coverage:
- Inner Tracker:
Added detailed hit count information, here on TFPX Disk 1:
- Outer Tracker:
Added detailed hit count information, here on TBPS Layer 1:
Stub coverage:
- Inner Tracker:
Introduce 'stub' in the Inner Tracker (offline sense):
1 stub   <->   (>= 2 hits) / layer
Added detailed stub count plots.
Added average number of stubs over eta.
- Outer Tracker:
Added detailed stub count plots.
> Inner Tracker 'offline' stubs + Detailed hits counts in IT and OT + Detailed stubs count in IT and OT

- config/stdinclude/CMS_Phase2/Pixel/Materials/module_FPIX2_v2_R2_2x2_2500
- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_2_1x1_25x100
- geometries/CMS_Phase2/OT614_200_IT450.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/FPIX2_4_4_1.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/FPIX2_4_5_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V4/Pixel_V4_5_0.cfg
- geometries/CMS_Phase2/readme.txt
- Add IT450: TEPX rings are radially equidistant. 
This is a first attempt to try to have the number of IT stubs ~uniformly distributed in radius.
This will need further tuning, since, for a given r-overlap, the stubs rates is higher at inner radius, due to phiOverlap effects.
TEPX:
From IT404:
Ring 2: Rhigh: 149 mm -> 145 mm.
Ring 3: Rhigh: 188.5 mm -> 182 mm.
Ring 4: Rhigh: 232 mm -> 219 mm.
The resulting radial spacings are, using (Ring (i) Rhigh)  - (Ring (i+1) Rmin):
i=1: 7.2 mm
i=2: 7.2 mm
i=3: 7.2 mm
i=4: 9.2 mm
+ Off-topic: Update IT440 and IT441: switch to 2x2 modules in TEPX Ring 2.
Hence, in the 'Swiss layout', there is now only 2 types of modules: 1x1 and 2x2 modules.
> Add IT450 for luminosity studies

- include/Analyzer.hh
- include/AnalyzerTools.hh
- include/global_constants.hh
- src/Analyzer.cc
This is gathered in an independent mini-PR, as it makes it much harder to check for regressions.
> Set the geometry coverage plots maxY (for comparison between layouts purposes)

- geometries/CMS_Phase2/Pixel/Pixel_V4/stations_BPIX_Service_Cylinder_V2
BPX conversion stations on service cylinder are now nearly adjacent, from Z = 430 mm to Z = 820 mm. Since they are 2 mm thick only, making them shorter result in a huge MB concentration in one spot only. 
To be further adjusted by Andre.
> Mini-PR: Adjusted Z positions of BPX conversion stations on service cylinder in IT461

- Makefile
- include/PlotDrawer.hh
- include/RootWeb.hh
- include/Vizard.hh
- src/ReportIrradiation.cc
- src/RootWeb.cc
- src/Vizard.cc
There was a heavy and unnecessary use of TCanvas::DrawClone().
This was is order to avoid transferring TCanvas objects ownership from Analyzer & Vizard to RootWeb.
This was considerably increasing run time.
Since TCanvas has no move semantics, just use unique_ptr<TCanvas> in the caller code instead!!
> Avoid TCanvas::DrawClone() 

- geometries/CMS_Phase2/OT614_200_IT612.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/FPIX2_6_1_1.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/FPIX2_6_1_2.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/Pixel_V6_1_2.cfg
- geometries/CMS_Phase2/readme.txt
- include/DetectorModule.hh
- include/Extractor.hh
- include/InnerCabling/GBT.hh
- include/InnerCabling/PowerChain.hh
- include/InnerCabling/inner_cabling_functions.hh
- include/Ring.hh
- include/tk2CMSSW_datatypes.hh
- src/Disk.cc
- src/Extractor.cc
- src/InnerCabling/ModulesToPowerChainsConnector.cc
- src/InnerCabling/PowerChain.cc
- src/InnerCabling/inner_cabling_functions.cc
- src/Ring.cc
- src/Tracker.cc
- xml/pixfwd.xml
- xml/trackerVolumeTemplate.xml
bigDelta: distance in Z between the center of a disk and the center of a ring.
smallDelta: distance in Z between the center of a ring and the center of a module.
Adds support for smallDelta > bigDelta case.
Obviously still need to keep support for smallDelta < bigDelta.
smallDelta > bigDelta: Modules of a ring are placed on 4 dees.
smallDelta < bigDelta: Modules of a ring are placed on 2 dees: half of the modules on each dee side.
See page 4 at https://indico.cern.ch/event/746593/contributions/3164208/attachments/1726785/2789605/EPIX_Geometry_02102018.pdf.
In practice, what needed to be adapted was:
- Added info on Ring and EndcapModule classes about how the configuration is.
Ring::isRingOn4Dees() (is smallDelta > bigDelta ?)
Ring::isSmallerAbsZRingInDisk() (is ring placed at -bigDelta in …
> Adds support of new rings paradigm in TEPX

- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD1_V616_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V616_200.cfg
- include/OuterCabling/ServicesChannel.hh
- include/global_constants.hh
- src/Squid.cc
- src/Vizard.cc
Cabling map on new envelope OT is accessible here: http://ghugo.web.cern.ch/ghugo/layouts/cabling/OT616_200_IT404/cablingOuter.html 
Changes that were auto made in cabling map:
TB2S: 2 rods less, hence 2 less MFBs per (Z) end.
TEDD_2: 8 modules less, hence smaller number modules per MFB for a few MFBs.
> Base OT cabling map on OT 616 by default + Added more detailed information on website on services channels (exchange with Axel)

- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_1x1_25x100
- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_1x1_50x50
- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_1x2_25x100
- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_1x2_25x100_short
- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_1x2_50x50
- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_2x2_25x100
- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_2x2_25x100_short
- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_2x2_50x200
- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_2x2_50x50
IT modules descriptions for old geometries (before change in pixel size): use a dead area length that avoids clashes in those geometries.
This is needed in preparing CMSSW geometries for TBPX services placement studies.
Indeed, these geometries are based on the non-skewed TBPX geometries, before change in IT modules size (this does not have any impact for this study anyway).
> Mini-PR: avoid overlaps in geometries with old IT modules sizes

- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD1_V616_200.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V616_200.cfg
- geometries/CMS_Phase2/readme.txt
There needs to be a 1 mm distance between the dee edge and the modules edges, instead of 1.5 mm. This results in: TEDD 1 and TEDD 2 inner: -0.5 mm. TEDD outer: +0.5 mm. 
**Summary of the changes in TEDD overall since TDR (615 rotated):** 
- bigDelta: 15.075 mm -> 15.755 mm (needed more disk separation).
- TEDD 1, inner rings: +7.041 mm (IT insertion) +0.51 mm (margin with dee edge).
- TEDD 2, inner rings: +2 mm (IT insertion) +0.51 mm (margin with dee edge).
- TEDD 1 and 2, outer rings: -27 mm (BTL) +0.41 mm (margin with dee edge).
- TEDD 2: -4 modules in Ring 7, -4 modules in Ring 14.
- Adjusted intermediate radii (needs feedback from Mechanics)
> Update TEDD 616 with feasability measures

- geometries/CMS_Phase2/OT614_200_IT613.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/BPIX_6_1_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/FPIX1_6_1_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/FPIX2_6_1_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/FPIX2_6_1_3.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/Pixel_V6_1_3.cfg
- geometries/CMS_Phase2/readme.txt
Stretched TEPX in Z (since there will be no dedicated lumi device).
TEPX last disk is set to be at the same meanZ as TEDD last disk. This will be further tuned when bulkhead design is advanced.
Removed tracking tag for TEDD Disk 4 Ring 1 (lumi ring).
Hence, that ring is not taken into accout in local param resolution plots AND tracking plots.
TO DO: Lumi ring still appears on hit counts on geo page.
Set the possibility to have INACTIVE hits on a module.
-> Module property: inactive
-> Change Hit constructor (with Module parameter) to avoid having all hits on module to be ACTIVE by default (use the Module property).
-> CHECK ALL ASSUMPTIONS in the code on hits on modules: should not assume them active by default. This is true for hit counts plots, but probably also at other places.
-> …
> Added IT 613: Stretched TEPX in Z + Remove trackingTag on lumi ring

- README.md
- setupCMake_slc6.sh
- setup_slc6.sh
Notes:
- gcc 
gcc 4.7 not available anymore in /contrib, but found it in /external
- BOOST 
BOOST 1.55.0_python2.7 not available anymore for x86_64-slc6-gcc47 architecture, but found for x86_64-slc6-gcc48 architecture.
Linker errors as described in https://svn.boost.org/trac10/ticket/10038#no1 appear with simple move to /cvmfs/sft.cern.ch/lcg/releases/Boost/1.55.0_python2.7-70d89/x86_64-slc6-gcc48-opt/
They could not be resolved with dirty trick provided at https://codeyarns.com/2017/09/20/undefined-reference-to-boost-copy_file/.
Eventually solved this by downgrading to Boost 1.50.0_python2.7, which does not require any dirty trick :)
> Phase-out of AFS: move all dependencies to CVMFS (with no need of local install)

- include/DetectorModule.hh
- include/OuterCabling/ModulesToBundlesConnector.hh
- include/OuterCabling/outer_cabling_constants.hh
- include/PlotDrawer.hh
- setupCMake_slc6.sh
- setup_slc6.sh
- src/AnalyzerVisitors/GeometricInfo.cc
- src/OuterCabling/ModulesToBundlesConnector.cc
- src/Vizard.cc
OT cabling map, TEDD: 
Each MFB has 4 fanout branches, for the connections to modules.
The logics used to be simple: for each MFB, 1 fanout branch per disk surface.
Now, there is the need, for each MFB, in case the modules of a given disk (not double-disk!) belong to different dees, to make an assignment per dee instead.
This is fully automated, so that the Mechanics can pick up whatever is in AggregationsPatterns.csv
All results are at: http://ghugo.web.cern.ch/ghugo/layouts/cabling/OT616_200_IT404/cablingOuter.html 
One can visualize the connections at the 'modules to bundles' section on the webpage. 
For example, if you look at the 'Positive cabling side', you can look at the 4 surfaces of DD 1, TEDD1.
The alternation of colors show the alternation of MFBs the modules end up connected …
> Merged friday's code: Assign MFB fanout branches to modules in TEDD

- geometries/CMS_Phase2/readme.txt
- src/Layer.cc
- src/OuterCabling/ModulesToBundlesConnector.cc
- src/Vizard.cc
This allows to change design. It comes from a misinterpretation from the Mechanics, that would be hard to correct on their side. 
This change in tracker design should obviously have no impact on tracker performance.
> Adds support for bigParity on tilted rods phi placement. 

- geometries/CMS_Phase2/OuterTracker/Tilted/TBPS_V615_200.cfg
- geometries/CMS_Phase2/readme.txt
This is to avoid having to many changes in OT615-> OT616 layout transition.
> Mini-PR: Also incorporates the flip of bigParity in OT615

- README.md
- geometries/CMS_Phase2/OT616_200_IT613.cfg
- src/Extractor.cc
- Adds OT616 on top of IT613.
- Alternation in phi of inner / outer radii rods in TBPS was flipped.
Fix issue in cone shape extrema calculation.
Cleaned ladder phi placement (would have assigned outer radii to RadisuIn parameter in PhiAltAlgo, which would have worked, but is very ugly).
- Adds warning for TBPX export.
Skewed TBPX ladders phi placement is incorrect by default. 
Skewed Barrel XML export should be done!!
NB: Extractor.cc code is very ugly (not mine ;p), would need to bin evth, and simply starts from a geometry visitor!
> Add OT616_IT613 combination + Fixes in XML export to support that geometry

- ROOT-env.sh
- setupCMake_slc6.sh
- setup_slc6.sh
As described in https://root-forum.cern.ch/t/root-production-release-v6-14-00-is-out/29360/23 
The use of LCG views break fonts, emacs,etc on slc6.
This allows to use the latest environment, without anything broken on slc6 :)
TO DO: Also need to provide support for CC7, as lxplus is switching to it.
> Fixed regressions of new environment on slc6

- setup_centos7.sh
On 2019 April 2, lxplus switches to centos7, so it is absolutely vital to add support for centos7.
This is fully operational.
Warning: TO DO: minor issue with Fontconfig (which appears on other platforms as well).
> Add support for centos7

- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_1x2_50x50_wide
- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_2x2_50x50_wide
- geometries/CMS_Phase2/OT616_200_IT620.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/BPIX_6_2_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/FPIX1_6_2_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/FPIX2_6_2_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/Pixel_V6_2_0.cfg
- geometries/CMS_Phase2/readme.txt
- include/VizardTools.hh
- src/Vizard.cc
- Add 'zebra' layout with layers alternatively with 25x100 and 50x50 modules.
Innermost TBPX layer and last TEPX disk are with 25x100 modules.
**Reference:** ![](http://ghugo.web.cern.ch/ghugo/layouts/test/OT616_200_IT613/img042.png)
**Zebre:** ![](http://ghugo.web.cern.ch/ghugo/layouts/test/OT616_200_IT620/img042.png)
_Color code:_
green: 1x2, 25x100
orange: 2x2, 25x100
blue:1x2, 50x50
yellow:2x2, 50x50
**Reference:** http://cms-tklayout.web.cern.ch/cms-tklayout/layouts-work/repository-git-dev/OT616_200_IT613/errorstracker.html 
**Zebre:** http://cms-tklayout.web.cern.ch/cms-tklayout/layouts-work/repository-git-dev/OT616_200_IT620/errorstracker.html 
- Also fix an issue in rounding, leading to wrong stripLength being displayed in the modules table on website.
> Add 'zebra' layout IT 620: alternation of 25x100 and 50x50 modules 

- include/AnalyzerVisitors/GeometricInfo.hh
- include/DetectorModule.hh
- include/InnerCabling/GBT.hh
- include/InnerCabling/InnerCablingMap.hh
- include/InnerCabling/ModulesToPowerChainsConnector.hh
- include/InnerCabling/PowerChain.hh
- include/InnerCabling/inner_cabling_constants.hh
- include/InnerCabling/inner_cabling_functions.hh
- include/PlotDrawer.hh
- include/Vizard.hh
- include/global_constants.hh
- src/AnalyzerVisitors/GeometricInfo.cc
- src/InnerCabling/InnerCablingMap.cc
- src/InnerCabling/ModulesToPowerChainsConnector.cc
- src/InnerCabling/PowerChain.cc
- src/InnerCabling/inner_cabling_functions.cc
- src/Squid.cc
- src/Vizard.cc
Adaptations to have the IT cabling map automatically computed on IT 613, which is now the default layout for the IT cabling map (instead of IT 404).
All results at:
http://ghugo.web.cern.ch/ghugo/layouts/IT_cabling/OT616_200_IT613/cablingInner.html 
Adaptations:
- **Changed number of e-links / module in TEPX Rings 1 and 2** (due to 2x2 modules instead of 1x2 modules, but also because of data rate in TEPX Ring 1).
- **Changed total number of modules which can be connected to the same serial power chain** (from 10 to 12).
- **Reimplemented isLongBarrel()**.
There was a regression. Now made it independent from the number of modules in a serial power chain.
- **Reimplemented intensity of current in serial power chain**.
There was a regression. Was previously dependent on ringNumber, now made …
> IT cabling map: Adaptations in the code to have it computed on IT 613 (instead of IT 404)

- include/CoordinateOperations.hh
- include/DetectorModule.hh
- include/Hit.hh
- include/Track.hh
- src/Analyzer.cc
- src/DetectorModule.cc
- src/Hit.cc
- src/Track.cc
Introduce a generic vectorial formula to compute track incident angles alpha and beta.
The new formula extends the old formulae, which were only 'projections' of the generic formula into planes.
alpha and beta angles are from Fig. 9 from [1].
This allow to have the incident angles directly computed for any sensor orientation in space. 
Notably, here, this allows to have correct calculation of the incident angles in the case of skewed ladders (was in the to-do list).
This new, more generic formula, also ends up being more accurate. It reveals dependencies which were not thought of in the following cases:
- alpha calculation (in the forward).
- beta angle depends mostly on track vector's theta, but actually depends on track vector's phi as well! (everywhere).
[1] …
> Introduce a generic vectorial formula to compute track incident angles. 

- config/stdinclude/CMS_Phase2/Pixel/Conversions/On_services_cylinder/stations_serving_TBPX_614
- config/stdinclude/CMS_Phase2/Pixel/Conversions/On_services_cylinder/stations_serving_TFPX_614
- geometries/CMS_Phase2/Pixel/Pixel_V6/BPIX_6_1_4.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/FPIX1_6_1_4.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/Pixel_V6_1_4.cfg
Same as IT 613 but with:
Disk 6 : -15 mm.
Disk 7: + 15mm.
TBPX conversion stations placed between Disk 6 and Disk 7.
**IT 613:**
**IT 614:**
> Add IT 614: TBPX portcards placed between TFPX disks 6 and 7.

- config/stdinclude/CMS_Phase2/Pixel/Conversions/On_services_cylinder/stations_serving_TBPX_616
- config/stdinclude/CMS_Phase2/Pixel/Conversions/On_services_cylinder/stations_serving_TFPX_615
- config/stdinclude/CMS_Phase2/Pixel/Conversions/On_services_cylinder/stations_serving_TFPX_616
- geometries/CMS_Phase2/OT616_IT615.cfg
- geometries/CMS_Phase2/OT616_IT616.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/BPIX_6_1_6.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/FPIX1_6_1_5.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/FPIX1_6_1_6.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/Pixel_V6_1_5.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/Pixel_V6_1_6.cfg
- geometries/CMS_Phase2/readme.txt
**IT 615:** 
http://ghugo.web.cern.ch/ghugo/layouts/T17/OT616_IT615/materialpixel.html 
TFPX: Stretched double-disk system, data from Yadira. 
- smallDelta: 2 -> 2.75 mm. 
Sensors on both faces of same dee: inter sensor centers distance (in Z) is now 5.5 mm.
- bigDelta: 4 -> 6.25 mm.
Back sensors of one dee VS front sensors of next dee: inter sensor centers distance (in Z) is now 7 mm.
**IT 616:** 
http://ghugo.web.cern.ch/ghugo/layouts/T18/OT616_IT616/materialpixel.html
TFPX: Tested shift in Z of +25 mm on all double-disks.  
See: https://indico.cern.ch/event/866839/contributions/3657003/attachments/1954592/3246242/Latest_Tracker_geometries_to_CMSSW.pdf
> Add latest TFPX

- config/stdinclude/CMS_Phase2/Pixel/Resolutions/100x100
- config/stdinclude/CMS_Phase2/Pixel/Resolutions/25x100
- config/stdinclude/CMS_Phase2/Pixel/Resolutions/50x200
- config/stdinclude/CMS_Phase2/Pixel/Resolutions/50x50
No major diff, reso slightly improved (since lower threshold).
IMPORTANT: param for 50x200 not updated.
Before PR:
- http://ghugo.web.cern.ch/ghugo/layouts/test/OT616_IT614_old_reso/layoutpixel.html 
After PR:
- http://ghugo.web.cern.ch/ghugo/layouts/test/OT616_IT614_new_reso/layoutpixel.html
> Riccardo s new parametrization: lower threshold: 1500 e- -> 1000 e-

- config/stdinclude/CMS_Phase2/Pixel/Resolutions/25x100
Recent update in parametrization: Lower threshold: 1500 e- -> 1000 e-
The shape at normal incidence (when lorentz angle = 0) was a hole, which was not expected.
> Riccardo s new parametrization: minor correction in 25 um parametrization.

- config/stdinclude/CMS_Phase2/OuterTracker/Materials/ModuleMaterials/Components/2S_1Strip_referenceSensors
- config/stdinclude/CMS_Phase2/OuterTracker/Materials/ModuleMaterials/pt2S_1Strip_320_18_components
- config/stdinclude/CMS_Phase2/OuterTracker/Materials/pt2S_1Strip_320_18
- config/stdinclude/CMS_Phase2/OuterTracker/ModuleTypes/pt2S_1Strip_320
- geometries/CMS_Phase2/OT617_IT613.cfg
- geometries/CMS_Phase2/OT617_IT615.cfg
- geometries/CMS_Phase2/OT618_IT615.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/OT_V617.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/OT_V618.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD1_V617.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V617.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V618.cfg
- geometries/CMS_Phase2/readme.txt
- All TEDD: update smallDeltas to latest info.
PS 4 mm: 7.375 mm -> 7.550 mm.
2S 4 mm:  8.550 mm -> 8.595 mm.
2S 1.8 mm: 7.450 mm -> 7.495 mm.
- Improve transition region between TB2S and TEDD by removing readout hybrid in TEDD1, R15.
Special modules in TEDD1, R15, with halved number of strips / module. WARNING: MODULE MB NOT UPDATED!!
Outer radius increased by 20.47 mm : R15 sensors centers: 1023.16 mm -> 1043.63 mm.
Radii in TEDD1, R12, R13, R14 adjusted accordingly.
- OT618: do the same thing on TEDD 2 R15 as well.
- The idea behind this is to reduce the gap at eta ~ 1.05.
OT 617 layout might never be built, if the performance is not shown to improve significantly.
OT 618 layout is not likely to be built, since TEDD 2 design (Lyon) is already frozen.
> Add OT 617 (and OT 618): Increase TEDD outermost radius to improve transition with TB2S (and TBPS)

- include/AnalyzerTools.hh
- include/global_constants.hh
- src/Analyzer.cc
- src/Vizard.cc
- deltaEta : 0.1 -> 0.02 on all plots.
- removed spot markers, which are hiding the interesting information.
This allows to see (hence understand...) way better the geometric coverage, as well as the details of the tracking resolution.
NB: deltaEta has 2 exceptions:
- deltaEta = 0.04 in 'Distribution of number of stubs per track' plots.
- deltaEta = 0.01 in 'Number of layers with at least a hit' plots. Might be nice to have it as well for the 'Number of hits' plots.
> Fix binning in info + geometry + tracking resolution plots

- config/stdinclude/CMS_Phase2/SimParms
- include/Hit.hh
- include/Track.hh
- src/Hit.cc
- src/Track.cc
**R-Phi resolution:**
Only the **strip length** was considered to compute the radial uncertainty.
The track's deltaTheta should be considered as well. 
This lead to TEDD R-Phi resolution being far too bad : only the 2S sensors 's very long strips were used to compute the radial uncertainty. 
Hence, TEDD impact on pT resolution was under-estimated.
In TFPX, TEPX, tilted TBPS and TEDD PS, this was also true. 
But in these subdetectors, the strip length is much shorter, making this effect completely negligible.
NB: deltaTheta needs to be computed once all hits along a track have been looked at.
This implies that the track's RZ uncertainty is computed first.
Then, the resulting track's deltaTheta is used to compute the R-Phi uncertainty.
> IMPORTANT: Fixed major issue in pT resolution

- src/Track.cc
Fix issues in pattern reco when propagateOutIn == false. 
- Need to properly propagate the propagateOutIn bool.
- When Track::getDeltaTheta is called and propagateOutIn == false, the track's hits are resorted, which needs to be corrected back to what we want in Track::computeCovarianceMatrixRPhi.
This lead to zillions of messages on the log page, blocking the nightlies.
> Fix nightlies (issues in pattern reco when propagateOutIn == false)

- src/Track.cc
- src/Vizard.cc
- Pettern reco run time: is divided by 2 by avoiding re-sorting hits several times, and wisely doing the sorting at the points where actually needed.
- Info page: IT parameters not properly displayed.
> Fix run time issues

- include/Extractor.hh
- include/XMLWriter.hh
- include/tk2CMSSW.hh
- include/tk2CMSSW_strings.hh
- src/Extractor.cc
- src/XMLWriter.cc
- src/tk2CMSSW.cc
Since introduction of MTD:
- the OTST is placed directly inside the Tracker volume.
- the OTST is described in a dedicated file (otst.xml).
Until now, OTST stayed static in CMSSW, and did not benefit from the updates from Mechanical engineers, which were studied and debugged in tkLayout.
As was in the to-do list for a long time:
**create an automatic export of the OTST.**
The difficulty lied in that the OTST needs to be seen as a different subdetector by tkLayout XML export, because it needs to be placed in its dedicated file, with its dedicated DD sections.
This allows to introduce the latest description of the OTST from Mechanics:
- CFRP skin thickness: 2 mm -> 4 mm. This explains a factor ~2 in the OTST weight!
- CFRP skin density: 1690 kg/m^3 -> 1550 kg/m^3.
- half length is updated …
> Export to CMSSW: Automatic export of OTST, with no clash with BTL

- src/OuterCabling/ServicesChannel.cc
This results in a shift of the channels used for powering.
NB: No change in the channels assignments mapping itself though! Just a shift of the sections available for powering.
**Power cables channels:**
**(+Z) end:** 
1C->1A, 3C->3A, etc. 
**(-Z) end:** 
-2A -> -2C, -4A -> -4C, etc. 
**Before PR:**
http://ghugo.web.cern.ch/ghugo/layouts/cabling/OT616_200_IT404/cablingOuter.html 
Barrel, (+Z) end:
TEDD Disk 1, (+Z) end:
**After PR:**
http://ghugo.web.cern.ch/ghugo/layouts/cabling/OT616_IT615_cooling_update/cablingOuter.html
Barrel, (+Z) end:
TEDD Disk 1, (+Z) end:
>  Update from Mechanics: now using different services channels for the cooling pipes.

- include/InnerCabling/GBT.hh
- src/AnalyzerVisitors/GeometricInfo.cc
- src/InnerCabling/GBT.cc
Simply used:
GBT Id = power chain id x 10 + GBTIndexInPowerChain. 
This is not as compact as it could be (not all consecutive integers values are used).
But much safer and easier to debug, and values are quite small anyway.
**After PR:** 
http://ghugo.web.cern.ch/ghugo/layouts/cabling/OT616_IT613_IT_cabling_map_for_CMSSW/cablingInner.html
> Inner cabling map: Add GBT Id scheme for CMSSW integration

- include/InnerCabling/GBT.hh
- include/InnerCabling/InnerCablingMap.hh
- include/InnerCabling/InnerDTC.hh
- src/AnalyzerVisitors/GeometricInfo.cc
- src/InnerCabling/GBT.cc
- src/InnerCabling/InnerCablingMap.cc
- src/InnerCabling/InnerDTC.cc
- src/Vizard.cc
Created CMSSW GBT and DTC Id schemes, not convenient for debugging, but better for the cabling map (in CMSSW) to be run on GPUs.
- GBTs CMSSW Ids are consecutive integers, and they are Ids PER DTC (from 1 to 60 max).
- DTCs are consecutive integers (from 1 to 28).
After PR: http://ghugo.web.cern.ch/ghugo/layouts/cabling/OT616_IT613_CMSSW_Ids/cablingInner.html
> Inner cabling map: Created CMSSW Id schemes for GBTs and DTCs (cache friendly for runs on GPUs)

- include/InnerCabling/inner_cabling_constants.hh
- src/InnerCabling/InnerCablingMap.cc
Add a shift of 216 (number of OT DTCs) to the IT DTC CMSSW Ids. 
This allows to have all Tracker DTCs Ids consecutive integers, from 1 to 216 + 28 = 244.
> Minor-PR: Inner cabling map: consistent scheme for full Tracker

- geometries/CMS_Phase2/OT800_IT615.cfg
- geometries/CMS_Phase2/OT800_IT621.cfg
- geometries/CMS_Phase2/OT800_IT700.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/OT_V800.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TBPS_V800.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD1_V800.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TEDD2_V800.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/BPIX_6_2_1.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/FPIX1_6_2_1.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/FPIX2_6_2_1.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/Pixel_V6_2_1.cfg
- geometries/CMS_Phase2/readme.txt
In view of PR to CMSSW.
**OT 800:**
- All TEDD: 
Update smallDeltas to latest info. Identical to the smallDelta updates in OT617. 
Excluding all the other updates in OT617 though (related to special 2S module in R15 and radii adjustments).
- TBPS:
Adjustments in Layer 1 to enable a safe IT installation, while respecting needed spacing with TBPS Layer 2 (supports and services).
Layer 1, Ring 12-16: radius +0.5 mm, tiltAngle 74 -> 72 deg.
**IT 621:** 
IT 615 with 50x50 pixel aspect ratio.
Ref: http://cms-tklayout.web.cern.ch/cms-tklayout/layouts-work/repository-git-dev/OT616_IT615/layout.html
OT 800: http://ghugo.web.cern.ch/ghugo/layouts/T21/OT800_IT615/layout.html 
IT 621: http://ghugo.web.cern.ch/ghugo/layouts/T22/OT800_IT621/layoutpixel.html
> Add OT 800 and IT 621 

- geometries/CMS_Phase2/OT800_IT701.cfg
- geometries/CMS_Phase2/OT801_IT701.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/OT_V801.cfg
- geometries/CMS_Phase2/OuterTracker/Tilted/TB2S_V801.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V7/FPIX1_7_0_1.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V7/Pixel_V7_0_1.cfg
- geometries/CMS_Phase2/readme.txt
- src/RodPair.cc
**- OT 801:**
TB2S: inter-ladder radial spacing increased by 1 mm (smallDelta: 2.25 mm -> 2.75 mm). Z positions recomputed.
**- IT 701:**
TFPX: Change of ring paradigm: modules of the same ring are now on 2 different dees, instead of being on both sides of the same dee.
This model is already used in TEPX. 
This makes the dee model mecanically feasible (cut at X~0), and better equilibrates services distribution among disks.
> Add OT 801 (new TB2S with increased inter-ladder spacing) and IT 701 ('a la TEPX' dee model)

- xml/pixfwd.xml
- xml/trackerVolumeTemplate.xml
NB: In CMSSW, I placed **FBCM volume outside of Tracker volume, directly inside OCMS** (instead of being inside Tracker volume).
I find it safer and nicer to keep a consistent Tracker volume (with no FBCM inside). This will avoid regressions further downstream in CMSSW.
CMSSW PR to FBCM private repo at: https://github.com/m-sedghi/cmssw/pull/1
> FBCM in CMSSW: Cut out Tracker volume to leave space for FBCM

- README.md
- setupCMake_centos7.sh
- setupCMake_slc6.sh
Usually just directly using make, but added setupCMake_centos7.sh for CMake users.
> CMS Phase 2 branches: Add CMake setup for Centos7

- xml/trackerVolumeTemplate.xml
In previous try to cut-out the FBCM volume (belongs to BRIL) from the tracker volume, the minus side was missed to be shortened on the PR [tkLayout:PR543](https://github.com/tkLayout/tkLayout/pull/543) at the commit [Cut out Tracker...](https://github.com/tkLayout/tkLayout/pull/543/commits/dba9dc2d6fbaa11d175ab76dca1a1b4b9e44911d). 
At this stage, the minus part of the tracker volume is also cut-out to make space for FBCM at the minus end.
> Fixing the tracker volume cut-out at the minus end for FBCM

- geometries/CMS_Phase2/OT800_IT702.cfg
- geometries/CMS_Phase2/OT800_IT703.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V7/BPIX_7_0_2.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V7/Pixel_V7_0_2.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V7/Pixel_V7_0_3.cfg
- geometries/CMS_Phase2/readme.txt
As per the PR title: adds two new IT geometries (IT702 and IT703), both with 3D pixels in TBPX L1 *only*, and 
(IT702/T25): 25x100 um2 planar sensors in the other TBPX layers and TFPX&TEPX 
(IT703/T26): 25x100 um2 planar sensors in the other TBPX layers and 50x50 um2 planar sensors in TFPX and TEPX
> Adding OT800_IT702 (T25) and OT800_IT703 (T26)

- src/Palette.cc
Just for reference, do not merge (yet?)
Currently ROOT colors are used instead of original clones of LibreOffice, to be able to later open a root file. This patch changes slightly the way colors will be displayed as the c…ode is running, but not the colors as they are saved in the ROOT file.
It has possible consequences on performance, and it was not tested for regression on transparent colors, so it should not be accepted.
> Restoring exact LibreOffice colors in display?

- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_1x2_25x100_wide_bricked
- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_2x2_25x100_wide_bricked
- include/Sensor.hh
- include/tk2CMSSW_datatypes.hh
- include/tk2CMSSW_strings.hh
- src/Extractor.cc
- src/XMLWriter.cc
This adds a new bricked module type so the `isBricked` property can be written into the XML's. Nothing changes in the TkLayout analysis (no new resolutions etc.), at this point really just to make it easier to set the property in the XML's correctly. 
No configs included in the PR for now, but an example geometry can be found here: https://adewit.web.cern.ch/adewit/layouts/OT800_IT700_BRICKED/info.html
> Bricked export

- include/InnerCabling/GBT.hh
- include/InnerCabling/InnerCablingMap.hh
- include/InnerCabling/PowerChain.hh
- include/InnerCabling/inner_cabling_constants.hh
- include/PlotDrawer.hh
- include/global_constants.hh
- src/DetectorModule.cc
- src/InnerCabling/GBT.cc
- src/InnerCabling/InnerCablingMap.cc
- src/Vizard.cc
This PR gathers several recent changes & brainstormings which were hanging around.
- **Base the IT cabling map on the IT 701 layout as a default (instead of IT 613).** 
The relevant change here, from the cabling map point of view, is in TFPX, where the double-disk model becomes 'a la TEPX' (ie, the 2 disks in each double-disk become complementary in phi, instead of being complementary in R).
Check robustness of the code against all regressions.
-  **GBTs reshuffling in TBPX Layers 2 & 3 (to reduce number of portcards & GBTs)**
A possible (selected) portcard design, is to have a maximum of 3 LpGBTs (instead of 2 LpGBTs) per portcard.
In TBPX L2 and L3, the number of GBTs was not as small as it could be. There were 4 GBTs among modules connected to the same power chain, while only 3 GBTs …
> Latest IT cabling map flavor (notably, GBTs reshuffling in TBPX Layers 2 & 3)

- config/stdinclude/CMS_Phase2/Pixel/ModuleTypes/pixel_1x2_15x60_wide
- config/stdinclude/CMS_Phase2/Pixel/Resolutions/15x60
- geometries/CMS_Phase2/OT800_IT630.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/BPIX_6_3_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/FPIX1_6_3_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V6/Pixel_V6_3_0.cfg
- geometries/CMS_Phase2/readme.txt
Inner Tracker 6.3.0 is based on 6.1.5 (i.e. T21), but with small rectangular pixels in Layer 1 and FPIX Disk 1
Small pixels = 15um x 60 um
> Adding layout OT800_IT630

- geometries/CMS_Phase2/OT800_IT800.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V8/BPIX_8_0_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V8/FPIX1_8_0_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V8/FPIX2_8_0_0.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V8/Pixel_V8_0_0.cfg
This adds the configs for T27 (OT800_IT800), following the proposed setup [here](https://indico.cern.ch/event/988838/contributions/4258167/attachments/2202703/3736635/em20210305.pdf#page=10) - this geometry was also introduced in CMSSW via [this PR](https://github.com/cms-sw/cmssw/pull/34120).
EDIT: I forgot to mention that this includes bricked pixels in part of the IT.
> Adding T27 (OT800_IT800)

- Makefile
- include/DetectorModule.hh
- include/OuterCabling/ModulesToBundlesConnector.hh
- include/OuterCabling/OuterCablingMap.hh
- include/OuterCabling/OuterGBT.hh
- include/Squid.hh
- include/Vizard.hh
- src/AnalyzerVisitors/GeometricInfo.cc
- src/DetectorModule.cc
- src/OuterCabling/ModulesToBundlesConnector.cc
- src/OuterCabling/OuterCablingMap.cc
- src/OuterCabling/OuterGBT.cc
- src/Squid.cc
- src/Vizard.cc
- src/tklayout.cc
In the OT there is one GBT per module, but (random) values are stored for the GBT ID in the cabling map in CMSSW. Much safer to have them written into the csv file that is used to create the cabling map to avoid anyone using a nonsensical number. This is the goal of this PR.
In addition, when both the IT and OT cabling maps are requested, a new page is added to the layouts page (e.g. https://adewit.web.cern.ch/adewit/layouts/OT800_IT700/cablingcombined.html ), which stores a combined csv file containing the mapping for both OT and IT, so that we don't need to merge the files manually when we want to create the CMSSW cabling map.
As for adding the GBT IDs to the OT cabling map, the approach here might seem particularly cumbersome (creating a module < > GBT class link, so that we create a …
> Add GBT links for OT

- geometries/CMS_Phase2/Pixel/Pixel_V8/BPIX_8_0_2.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V8/FPIX1_8_0_2.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V8/Pixel_V8_0_1.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V8/Pixel_V8_0_2.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V8/Pixel_V8_0_3.cfg
- geometries/CMS_Phase2/readme.txt
Does what it says on the tin - adding 3 new bricked pixel geometries (IT801), one used for private studies and two for integration into CMSSW (802,803)
> Adding new geometries with bricked pixels

- include/global_constants.hh
- src/Squid.cc
- src/tklayout.cc
In addition to the geometry the cabling map was designed/implemented for, have a list of "compatible" geometries for which the cabling maps will be produced when `--all` is specified.
> Run cabling when `--all` is specified for compatible geometries

- include/AnalyzerVisitors/IrradiationPower.hh
- include/ReportIrradiation.hh
- src/AnalyzerVisitors/IrradiationPower.cc
- src/ReportIrradiation.cc
This adds plots showing the number of modules seeing a given dose/fluence, as well as the normalised cumulative distribution (fraction of modules above a certain dose/fluence). 
Example results here: https://adewit.web.cern.ch/adewit/layouts/OT801_IT701_COPY/irradiation_Outer.html 
For the inner tracker, some of these plots are not filled because I made separate canvases for the different module spacings in the OT, and can't figure out how to not store an empty canvas (since the code is the same for IT and OT).  I won't have time to look into this in detail for the next several weeks but I don't think it is a showstopper for now since all the information should at least be there.
@alkemyst let me know what you think.
> Add dose/fluence plots

- geometries/CMS_Phase2/OT800_IT704.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V7/BPIX_7_0_4.cfg
- geometries/CMS_Phase2/Pixel/Pixel_V7/Pixel_V7_0_4.cfg
Wrong zOverlap was set for TBPX L2 - led to clash of dead areas (not active areas). This fixes that. 
NB *this replaces CMSSW model T25, the website still needs to be updated to reflect that*
> Adding IT704 - bug fix of IT702

- xml/pixbar.xml
To avoid clash between tracker volume and BTL. Does not affect positions of tracker modules
> Reduce Tracker2SOuterRadius by 2cm

- config/stdinclude/CMS_Phase2/Pixel/Materials/module_BPIX_L1_1x2_2500_2sens_3D
- config/stdinclude/CMS_Phase2/Pixel/ModuleMaterials/Components/pixel_Sensor_Dead_Area_1x2_2sens_3D
- geometries/CMS_Phase2/Pixel/Pixel_V7/BPIX_7_1_1.cfg
- src/Extractor.cc
- src/XMLWriter.cc
Fixed the inconsistent amount of material in the dead-area Si strips in the split-sensor PXB modules, used in `IT711` geometry.
Previously used weight of Si, inherited from `IT704`, was calculated for 33% smaller area (150um around one big sensor plane) compared to the split-sensor geometry: 175um around two smaller sensor planes.
This affects both the material budget/weights reported by tkLayout and the material density in the exported XMLs for CMSSW.
> Dead-area material in split-sensor PXB modules
